# Generated by Django 2.1.7 on 2019-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
